export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_REPOSITORIES_SUCCESS = 'LOAD_REPOSITORIES_SUCCESS';
export const LOAD_REPOSITORIES_ERROR = 'LOAD_REPOSITORIES_ERROR';
export const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS';
export const SEARCH_REPOSITORIES_ERROR = 'SEARCH_REPOSITORIES_ERROR';
export const LOAD_PULLS_SUCCESS = 'LOAD_PULLS_SUCCESS';
export const LOAD_PULLS_ERROR = 'LOAD_PULLS_ERROR';
